### ISSUE TITLE
Добавить метод получения деревьев пользователя

### ISSUE THREAD

**Issue by DonKeyHot1** [Yekaterinburg-Tree-Map/ekbtrees-backend#23]
Метод должен возвращать список деревьев, автором которых является пользователь, id которого приходит в метод

**Comment by yulia-matveeva** [comment]
https://github.com/Yekaterinburg-Tree-Map/ekbtrees-backend/tree/trees_current_user

**Comment by yulia-matveeva** [comment]
https://github.com/Yekaterinburg-Tree-Map/ekbtrees-backend/pull/27
